export const districtDB = {
  충청남도: "North Chungcheong",
  인천광역시: "Incheon",
  강원특별자치도: "Gangwon",
  서울특별시: "seoul",
  경기도: "Gyeonggi",
  전라남도: "North Jeolla",
  광주광역시: "Gwangju",
  충청북도: "South Chungcheong",
  대전광역시: "Daejeon",
  대구광역시: "Daegu",
  경상북도: "South Gyeongsang",
  전라북도: "South Jeolla",
  부산광역시: "Busan",
  울산광역시: "Ulsan",
  경상남도: "North Gyeongsang",
  제주특별자치도: "Jeju",
  세종특별자치시: "Sejong",
};
